# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - astra_arm_controller
    - hand_controller

  astra_arm_controller:
    type: FollowJointTrajectory
    joints:
      - axis_0_joint
      - axis_1_joint
      - axis_2_joint
      - axis_3_joint
      - wrist_yaw_joint
      - wrist_roll_joint
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - ef_gripper_left_joint
    action_ns: gripper_cmd
    default: true