# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    astra_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: velocity_controllers/JointGroupVelocityController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

astra_arm_controller:
  ros__parameters:
    joints:
    - axis_0_joint
    - axis_1_joint
    - axis_2_joint
    - axis_3_joint
    - wrist_yaw_joint
    - wrist_roll_joint
    command_interfaces:
    # - position
    - velocity
    state_interfaces:
    - position
    - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    gains:
      axis_0_joint:
        ff_velocity_scale: 1.0
      axis_1_joint:
        ff_velocity_scale: 1.0
      axis_2_joint:
        ff_velocity_scale: 1.0
      axis_3_joint:
        ff_velocity_scale: 1.0
      wrist_yaw_joint:
        ff_velocity_scale: 1.0
      wrist_roll_joint:
        ff_velocity_scale: 1.0

hand_controller:
  ros__parameters:
    joints:
    - ef_gripper_left_joint
