# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, ament-cmake, arm-description, controller-manager, joint-state-publisher, joint-state-publisher-gui, joint-trajectory-controller, moveit-configs-utils, moveit-kinematics, moveit-planners, moveit-ros-move-group, moveit-ros-visualization, moveit-ros-warehouse, moveit-setup-assistant, moveit-simple-controller-manager, robot-state-publisher, rviz-common, rviz-default-plugins, rviz2, tf2-ros, xacro }:
buildRosPackage rec {
  pname = "ros-humble-arm-moveit-config";
  version = "0.3.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ arm-description controller-manager joint-state-publisher joint-state-publisher-gui joint-trajectory-controller moveit-configs-utils moveit-kinematics moveit-planners moveit-ros-move-group moveit-ros-visualization moveit-ros-warehouse moveit-setup-assistant moveit-simple-controller-manager robot-state-publisher rviz-common rviz-default-plugins rviz2 tf2-ros xacro ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "An automatically generated package with all the configuration and launch files for using the ASTRA_Arm with the MoveIt Motion Planning Framework";
    license = with lib.licenses; [ bsd3 ];
  };
}
