# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, common-interfaces, controller-manager, diff-drive-controller, geometry2, ign-ros2-control, robot-state-publisher, ros-gz, ros2-control, xacro }:
buildRosPackage rec {
  pname = "ros-humble-core-gazebo";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ common-interfaces controller-manager diff-drive-controller geometry2 ign-ros2-control robot-state-publisher ros-gz ros2-control xacro ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "AGPL-3.0-only" ];
  };
}
