# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, geometry2, joint-state-publisher, rclpy, robot-state-publisher, rviz2, xacro }:
buildRosPackage rec {
  pname = "ros-humble-arm-description";
  version = "1.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ geometry2 joint-state-publisher rclpy robot-state-publisher rviz2 xacro ];

  meta = {
    description = "This package contains configuration data, 3D models and launch files for Clucky's arm";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
