# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, diff-drive-controller, geometry2, joint-state-publisher, rclpy, robot-state-publisher, ros2-control, rviz2, xacro }:
buildRosPackage rec {
  pname = "ros-humble-core-description";
  version = "1.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ diff-drive-controller geometry2 joint-state-publisher rclpy robot-state-publisher ros2-control rviz2 xacro ];

  meta = {
    description = "This package contains configuration data, 3D models and launch files for Clucky Core";
    license = with lib.licenses; [ "AGPL-3.0-only" ];
  };
}
