# Automatically generated by: ros2nix --flake --fetch --distro humble
{
  lib,
  buildRosPackage,
  fetchgit,
  ament-cmake,
  arm-description,
  arm-moveit-config,
  astra-msgs,
  core-description,
  core-gazebo,
}:
buildRosPackage rec {
  pname = "ros-humble-astra-descriptions";
  version = "1.0.0";

  src = fetchgit {
    url = "git@github.com:SHC-ASTRA/astra_descriptions";
    rev = "55116f70eed9f2de1983cc9b9f4a1e55bf9a5a74";
    sha256 = "0qca0bypdnh1cancgsrl6z0h1a59cjzn98pis8wf8qifdazj0x30";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/astra_descriptions/";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    arm-description
    arm-moveit-config
    astra-msgs
    core-description
    core-gazebo
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ASTRA's URDFs and their supporting files.";
    license = with lib.licenses; [ "AGPL-3.0-only" ];
  };
}
